### ISSUE TITLE
Installation instructions are not complete

### ISSUE THREAD

**Issue by davidnewcomb** [EvgeniyRRU/yii2-slick#1]
D:\Development\xampp\htdocs\rfc\yii-application>php D:\Application\bin\composer.phar require "evgeniyrru/yii2-slick" "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/jquery (2.1.3)
Reading bower.json of bower-asset/jquery (2.1.2)
Reading bower.json of bower-asset/jquery (2.1.1)
Reading bower.json of bower-asset/jquery (2.1.0)
Reading bower.json of bower-asset/jquery (2.0.3)
Reading bower.json of bower-asset/jquery (2.0.2)
Reading bower.json of bower-asset/jquery (2.0.1)
Reading bower.json of bower-asset/jquery (2.0.0)
Reading bower.json of bower-asset/jquery (1.11.2)
Reading bower.json of bower-asset/jquery (1.11.1)
Reading bower.json of bower-asset/jquery (1.11.0)
Reading bower.json of bower-asset/jquery (1.10.2)
Reading bower.json of bower-asset/jquery (1.10.1)
Reading bower.json of bower-asset/jquery (1.10.0)
Reading bower.json of bower-asset/jquery (1.9.1)
Reading bower.json of bower-asset/jquery (1.9.0)
Reading bower.json of bower-asset/jquery (1.8.3-patch1)
Reading bower.json of bower-asset/jquery (1.8.3)
Reading bower.json of bower-asset/jquery (1.8.2)
Reading bower.json of bower-asset/jquery (1.8.1)
Reading bower.json of bower-asset/jquery (1.8.0)
Reading bower.json of bower-asset/jquery (1.7.2)
Reading bower.json of bower-asset/jquery (1.7.1)
Reading bower.json of bower-asset/jquery (1.7.0)
Reading bower.json of bower-asset/jquery (1.7)
Reading bower.json of bower-asset/jquery.inputmask (3.1.61)
Reading bower.json of bower-asset/jquery.inputmask (3.1.60)
Reading bower.json of bower-asset/jquery.inputmask (3.1.59)
Reading bower.json of bower-asset/jquery.inputmask (3.1.58)
Reading bower.json of bower-asset/jquery.inputmask (3.1.57)
Reading bower.json of bower-asset/jquery.inputmask (3.1.56)
Reading bower.json of bower-asset/jquery.inputmask (3.1.55)
Reading bower.json of bower-asset/jquery.inputmask (3.1.54)
Reading bower.json of bower-asset/jquery.inputmask (3.1.53)
Reading bower.json of bower-asset/jquery.inputmask (3.1.52)
Reading bower.json of bower-asset/jquery.inputmask (3.1.51)
Reading bower.json of bower-asset/jquery.inputmask (3.1.50)
Reading bower.json of bower-asset/jquery.inputmask (3.1.49)
Reading bower.json of bower-asset/jquery.inputmask (3.1.48)
Reading bower.json of bower-asset/jquery.inputmask (3.1.47)
Reading bower.json of bower-asset/jquery.inputmask (3.1.46)
Reading bower.json of bower-asset/jquery.inputmask (3.1.45)
Reading bower.json of bower-asset/jquery.inputmask (3.1.44)
Reading bower.json of bower-asset/jquery.inputmask (3.1.43)
Reading bower.json of bower-asset/jquery.inputmask (3.1.42)
Reading bower.json of bower-asset/jquery.inputmask (3.1.41)
Reading bower.json of bower-asset/jquery.inputmask (3.1.40)
Reading bower.json of bower-asset/jquery.inputmask (3.1.39)
Reading bower.json of bower-asset/jquery.inputmask (3.1.38)
Reading bower.json of bower-asset/jquery.inputmask (3.1.37)
Reading bower.json of bower-asset/jquery.inputmask (3.1.36)
Reading bower.json of bower-asset/jquery.inputmask (3.1.35)
Reading bower.json of bower-asset/jquery.inputmask (3.1.34)
Reading bower.json of bower-asset/jquery.inputmask (3.1.33)
Reading bower.json of bower-asset/jquery.inputmask (3.1.32)
Reading bower.json of bower-asset/jquery.inputmask (3.1.31)
Reading bower.json of bower-asset/jquery.inputmask (3.1.30)
Reading bower.json of bower-asset/jquery.inputmask (3.1.29)
Reading bower.json of bower-asset/jquery.inputmask (3.1.28)
Reading bower.json of bower-asset/jquery.inputmask (3.1.27)
Reading bower.json of bower-asset/jquery.inputmask (3.1.26)
Reading bower.json of bower-asset/jquery.inputmask (3.1.25)
Reading bower.json of bower-asset/jquery.inputmask (3.1.24)
Reading bower.json of bower-asset/jquery.inputmask (3.1.23)
Reading bower.json of bower-asset/jquery.inputmask (3.1.22)
Reading bower.json of bower-asset/jquery.inputmask (3.1.21)
Reading bower.json of bower-asset/jquery.inputmask (3.1.15)
Reading bower.json of bower-asset/jquery.inputmask (3.1.14)
Reading bower.json of bower-asset/jquery.inputmask (3.1.13)
Reading bower.json of bower-asset/jquery.inputmask (3.1.12)
Reading bower.json of bower-asset/jquery.inputmask (3.1.0)
Reading bower.json of bower-asset/punycode (v1.3.2)
Reading bower.json of bower-asset/punycode (v1.3.1)
Reading bower.json of bower-asset/punycode (v1.3.0)
Reading bower.json of bower-asset/yii2-pjax (v2.0.2)
Reading bower.json of bower-asset/yii2-pjax (v2.0.1)
Reading bower.json of bower-asset/bootstrap (v3.3.2)
Reading bower.json of bower-asset/bootstrap (v3.3.1)
Reading bower.json of bower-asset/bootstrap (v3.3.0)
Reading bower.json of bower-asset/bootstrap (v3.2.0)
Reading bower.json of bower-asset/bootstrap (v3.1.1)
Reading bower.json of bower-asset/bootstrap (v3.1.0)
Reading bower.json of bower-asset/typeahead.js (v0.10.5)
Reading bower.json of bower-asset/typeahead.js (v0.10.4)
Reading bower.json of bower-asset/typeahead.js (v0.10.3)
Reading bower.json of bower-asset/typeahead.js (v0.10.2)
Reading bower.json of bower-asset/typeahead.js (v0.10.1)
Reading bower.json of bower-asset/typeahead.js (v0.10.0)
Reading bower.json of bower-asset/jquery (1.6.4)
Reading bower.json of bower-asset/jquery (1.6.3)
Reading bower.json of bower-asset/jquery (1.6.2)
Reading bower.json of bower-asset/jquery (1.6.1)
Reading bower.json of bower-asset/jquery (1.6.0)
Reading bower.json of bower-asset/jquery (1.6)
Reading bower.json of bower-asset/jquery-ui (1.11.3)
Reading bower.json of bower-asset/jquery-ui (1.11.2)
Reading bower.json of bower-asset/jquery-ui (1.11.1)
Reading bower.json of bower-asset/jquery-ui (1.11.0)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package evgeniyrru/yii2-slick could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

D:\Development\xampp\htdocs\rfc\yii-application>

**Comment by EvgeniyRRU** [comment]
Yes, I've seen it yesterday in my new project. I'll fix it through 1-2 days.

**Comment by EvgeniyRRU** [comment]
As I can see now it should working with stable version of Yii2 (I've added 1.0.0 version). Thank you for assistance.
