### ISSUE TITLE
Add load options

### ISSUE THREAD

**Issue by dmalykh** [EvgeniyRRU/yii2-slick#10]
Please add one more option to this widget.

public $position = View::POS_READY;

And at line 96:

$view->registerJs(implode(PHP_EOL, $js), $this->position);

With this option we can load js in every moment that we need.

**Comment by EvgeniyRRU** [comment]
Why not, I'll add it.

**Comment by EvgeniyRRU** [comment]
@dmalykh is [it](https://github.com/EvgeniyRRU/yii2-slick/pull/11/files) exactly what you need?

**Comment by dmalykh** [comment]
Yes! Thx!

**Comment by EvgeniyRRU** [comment]
Merged. I've updated package.
