### ISSUE TITLE
Error after Update 1.0.2

### ISSUE THREAD

**Issue by ExceptionHandling** [EvgeniyRRU/yii2-slick#13]
Slick.php, Line 109:
$view->registerJs(new JsExpression("$('#".$this->id."').on('"$key"', "$value");", $this->jsPosition));
correct:
$view->registerJs(new JsExpression("$('#".$this->id."').on('".$key."', ".$value.");", $this->jsPosition));

**Comment by EvgeniyRRU** [comment]
Oooh, shiii... I've merged PR. Will fix asap.

**Comment by EvgeniyRRU** [comment]
Fixed
