### ISSUE TITLE
Make the image responsive too.

### ISSUE THREAD

**Issue by MarcoDuizer** [EvgeniyRRU/yii2-slick#15]
At line 89 from slick.css i think adding the width: 100% will help a lot for being responsive. I added it and now when changing the width of the window the image scales nicely at the breakpoints.

.slick-slide img
{
    display: block;
    width: 100%;
}

**Comment by EvgeniyRRU** [comment]
Accordingly plugin source code (I mean Yii2 extension), there aren't any css files. You should to address your issue to [original JS plugin repository](https://github.com/kenwheeler/slick/).
