### ISSUE TITLE
Missing css file

### ISSUE THREAD

**Issue by davidnewcomb** [EvgeniyRRU/yii2-slick#2]
If you don't include slick-theme then the "dots" (and other) options have no effect.

class SlickAsset extends AssetBundle
{
    public $sourcePath = '@bower/slick-carousel/slick/';

```
public $css = [
    'slick.css'
    ,'slick-theme.css'     // Missing

];
```

**Comment by EvgeniyRRU** [comment]
Did your installed extension via Composer/Bower? As can I see, newest version in Bower doesn't require slick-theme.css. But it available in Github repository.
