### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by dominikchrastek** [EvgeniyRRU/yii2-slick#5]
Hi, I wanna use responsive breakpoints, but I don't know how it works.
There is image with my usage of this, can you help me please?
![screen shot 2015-05-21 at 11 35 21](https://cloud.githubusercontent.com/assets/9496259/7745698/7f44036e-ffad-11e4-86bb-04b9019e661a.png)

**Comment by EvgeniyRRU** [comment]
Sure, I used it in my last project. I'll publish example, maybe update Readme.md today at 20:00 UTC.

**Comment by dominikchrastek** [comment]
It will be awesome, if you publish example.

**Comment by EvgeniyRRU** [comment]
I've updated README.md file. See example.
