### ISSUE TITLE
Some problem with install

### ISSUE THREAD

**Issue by stylekrasota** [EvgeniyRRU/yii2-slick#6]
- evgeniyrru/yii2-slick dev-master requires bower-asset/slick-carousel \* -> no matching package found.
  - evgeniyrru/yii2-slick 1.0.0 requires bower-asset/slick-carousel \* -> no matching package found.
  - Installation request for evgeniyrru/yii2-slick \* -> satisfiable by evgeniyrru/yii2-slick[1.0.0, dev-master].

How can I fix it?

**Comment by EvgeniyRRU** [comment]
It seems, original plugin (slick.js) has changed bower package. I'll check it

**Comment by EvgeniyRRU** [comment]
It seems, my extension installs fine. 
![composer](https://cloud.githubusercontent.com/assets/3672367/9836499/d87c1bb4-5a1c-11e5-8348-49b3c2153d81.png)

Did you required [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin) before install Yii2 ?

``` bash
php composer.phar global require "fxp/composer-asset-plugin:~1.0.0"
```
