### ISSUE TITLE
The file or directory to be published does not exist: .../vendor/bower/slick-carousel/slick

### ISSUE THREAD

**Issue by guimarca** [EvgeniyRRU/yii2-slick#8]
Just installed the plugin and the follwoing exception pops:

Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: .../vendor/bower/slick-carousel/slick

It seems that in my app, that folder is in .../vendor/bower/**bower-asset/**slick-carousel/slick

It is then solved adding a symlink.

**Comment by EvgeniyRRU** [comment]
I suppose, authors original plugin (http://kenwheeler.github.io/slick/) has updated it again with breakbackward compatibility. I'll check it and fix.

**Comment by EvgeniyRRU** [comment]
I suppose, you changed bower assets directory in your .bowerrc file. My plugin based on _@bower_ alias, defined in `\yii\base\Application` at number 456 (https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L456).
