### ISSUE TITLE
Sliders not displayed on desktop

### ISSUE THREAD

**Issue by sadiq-mc** [EvgeniyRRU/yii2-slick#9]
Hi.. I am facing an issue with the slick which I faced same when I tried with normal slick plugin.
The issue is that the sliders/images are not displayed on desktop view when the ```slick-theme.css``` is present.. and if its removed, the previous/next button styling fails. 

I have raised the same issue in [slick's github](https://github.com/kenwheeler/slick/issues/2739), but no response yet.. Can you help to solve this issue.. 

```php
<?= Slick::widget([

	// HTML tag for container. Div is default.
	'itemContainer' => 'div',

	// HTML attributes for widget container
	'containerOptions' => ['class' => 'container'],

	// Items for carousel. Empty array not allowed, exception will be throw, if empty
	'items' => [
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 5.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 4.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 5.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 4.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 5.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 4.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 5.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 4.png'),
		Html::img(Yii::$app->request->baseUrl . '/images/Layer 5.png')
	],

	// HTML attribute for every carousel item
	'itemOptions' => ['class' => 'cat-image'],

	'clientOptions' => [
		'autoplay' => true,
		'autoplaySpeed' => 1500,
		'infinite' => false,
		'slidesToShow' => 6,
		'slidesToScroll' => 6,
		'responsive' => [
			[
				'breakpoint' => 1200,
				'settings' => [
					'slidesToShow' => 4,
					'slidesToScroll' => 4,
				],
			],
			[
				'breakpoint' => 600,
				'settings' => [
					'slidesToShow' => 3,
					'slidesToScroll' => 3,
				],
			],
			[
				'breakpoint' => 480,
				'settings' => [
					'slidesToShow' => 2,
					'slidesToScroll' => 2,
				],
			],

		],
	],

]); ?>
```

**Comment by EvgeniyRRU** [comment]
@sadiq-mc, I've answered you in original topic.

**Comment by EvgeniyRRU** [comment]
I close this issue, because it not about Yii2Slick widget

**Comment by sadiq-mc** [comment]
@EvgeniyRRU There was a div above this which had a class ```col-xs-12``` which was causing the layout to not display in the slider in the page while in desktop..

Commented [here](https://github.com/kenwheeler/slick/issues/2739#issuecomment-277184150)

If we add ```col-xs-12``` to the above div, add a grid system to ```containerOptions``` as well

**Comment by EvgeniyRRU** [comment]
@sadiq-mc I'll not do correct README.md file because you issue more about Twitter Bootstrap, not Slick.js

**Comment by sadiq-mc** [comment]
@EvgeniyRRU Its ok.. No issues... ;)
